// ATENÇÃO: Pode haver conflito de rotas com a pasta (communication)
// Considere renomear esta pasta ou a outra para evitar conflitos

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function CommunicationLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col h-full">
      {children}
    </div>
  )
}
